### ISSUE TITLE
LUT2 Question

### ISSUE THREAD

**Issue by Zika-dev** [schizolab/one-time-pad-tutorial#1]
The LUT2's encryption result can sometimes result in a number larger than 5, for example 52 would result in 7. However the table only contains 5 rows/columns so it's not possible to decrypt, unless I have misunderstood the decryption process.

**Comment by schizolab** [comment]
Let's say
A XOR B == C

Then it is true that: C XOR B == A, and C XOR A == B

Therefore, you find the 7 in the middle of the LUT, not the headers, and input the key from the vertical or horizontal header, and in another header it appears.

**Comment by schizolab** [comment]
Fixed in f3fe4c431a5f199504d96549bfd91b3e0fb8d422.

Thank you @Zika-dev, yeah I did cause some confusion.
